[package]
name = "aoc-2020-01-report_repair"
version = "0.1.0"
authors = ["Vasilis Gerakaris <vasilis.gerakaris@navarino.gr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
